;;; init.el

;;; Code:

;; Produce backtraces when errors occur: can be helpful to diagnose startup issues
;; (setq debug-on-error t)

;;; Load Path
(add-to-list 'load-path
	     (expand-file-name (concat user-emacs-directory "lisp")))

;;; site-lisp : 第三方 package
(add-to-list 'load-path "~/.emacs.d/site-lisp/")

;;; redirect the custom config generated by Custom to custom.el
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

;;; Require
(require 'init-encode)
(require 'init-var)

(require 'init-elpa)

;;;; built-in
(require 'init-ui)
(require 'init-misc)
(require 'init-ibuffer)
(require 'init-windows)
(require 'init-dired)
(require 'init-proxy)
(require 'init-vc)

(require 'init-org)

;;;; elpa
(require 'init-company)
(require 'init-counsel)
(require 'init-ido)
;; (require 'init-projectile)
(require 'init-evil)
(require 'init-ime)
(require 'init-packages)

;;;; site-lisp
(require 'init-eshell)
(require 'init-thing-edit)
(require 'init-auto-save)

;;;; local configs
(require 'init-local)

;; 如果有custom.el文件，就加载custom.el文件
;; 如果不加这局话。custom.el中的配置无法加载
;; (when (file-exists-p custom-file)
;;   (load-file custom-file))
(put 'narrow-to-region 'disabled nil)
(put 'narrow-to-page 'disabled nil)
